name: 06_deploy_and_sign

#on: [ push, pull_request ]
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to demo_app
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/demo_app.key
          chmod 600 ~/.ssh/demo_app.key
          cat >>~/.ssh/config <<END
            Host demo_app
            HostName ${{ secrets.HOST }}
            User demo_app
            IdentityFile ~/.ssh/demo_app.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Deploy
        run: ssh demo_app '/usr/local/bin/devops/deploy/deploy.sh'

      - name: Sign The Code
        run: ssh demo_app 'cd ~/deployments/current && php artisan app:sign-code'
